"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _posts_page from './posts-page.bones.json'
import _analytics_page from './analytics-page.bones.json'
import _calendar_page from './calendar-page.bones.json'
import _inbox_page from './inbox-page.bones.json'
import _recommendations_page from './recommendations-page.bones.json'
import _trends_page from './trends-page.bones.json'
import _billing_page from './billing-page.bones.json'
import _connections_page from './connections-page.bones.json'
import _admin_overview from './admin-overview.bones.json'
import _admin_teams from './admin-teams.bones.json'

registerBones({
  "posts-page": _posts_page,
  "analytics-page": _analytics_page,
  "calendar-page": _calendar_page,
  "inbox-page": _inbox_page,
  "recommendations-page": _recommendations_page,
  "trends-page": _trends_page,
  "billing-page": _billing_page,
  "connections-page": _connections_page,
  "admin-overview": _admin_overview,
  "admin-teams": _admin_teams,
})
